Add custom error response to support SPA URLs.
gohypergiant/terraform-aws-s3-static-site pull request #18
Opened 2020-08-28 12:56 UTC by jcookehg

2020-08-28 13:43 UTC, jcookehg commented
I could make this optional w/ something like:
`custom_error_response = [var.enable_spa == true ? locals. spa_custom_error_response : ""]`

2020-08-28 14:22 UTC, brandonjpierce approved these changes
H Y P E

2020-08-31 12:36 UTC, bbriggs requested changes
The structure of this looks good, but we should provide a safe default (and maybe couple it to the `error_document` var [here](https://github.com/gohypergiant/terraform-aws-s3-static-site/blob/314ebb717766ae06deea12c125e094664a485468/variables.tf#L24)

2020-09-03 14:08 UTC, bbriggs approved these changes

2020-09-03 14:10 UTC, merged